version: "2"

services:

  php:
    container_name: lumenapi_php
    image: bitnami/php-fpm
    volumes:
      - ./app:/app

  server:
    container_name: lumenapi_server
    image: bitnami/nginx
    ports:
      - 80:80
    volumes:
      - ./app:/app
      - ./site.conf:/bitnami/nginx/conf/vhosts/site.conf
